timezone: Australia/Melbourne
excerpt_separator: <!--more-->
name: paul.j.fenwick
description: "Some guy from the internet who loves freedom."
url: http://pjf.id.au/

exclude: 
    - '_assets'
    - 'bin'
    - 'CNAME'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile.rb'
    - 'README.md'


# addthis:
#    publisher: ra-52daa5464f2c1c4b

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
